[servers]
app3 ansible_host=10.23.5.31 ansible_connection=ssh
app4 ansible_host=10.23.5.32 ansible_connection=ssh
app5 ansible_host=10.23.202.28 ansible_connection=ssh


[servers:vars]
ansible_user=adilsongomes
ansible_password=''
ansible_become=yes
ansible_become_user=root
ansible_become_pass=''
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3